version: "3.7"

services:
  backend:
    container_name: pm2-backend
    build: .
    env_file:
      - .env
    command: /scripts/containers/backend.dev.sh
    networks:
      - internal
    ports:
      - ${BACKEND_PORT}:4000
    restart: always
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
      - ./configs:/configs
      - ./scripts:/scripts
  frontend:
    container_name: pm2-frontend
    build: .
    env_file:
      - .env
    command: /scripts/containers/frontend.dev.sh
    privileged: true
    networks:
      - internal
    ports:
      - ${FRONTEND_PORT}:5173
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
      - ./configs:/configs
      - ./scripts:/scripts
    restart: always
  mongodb:
    container_name: mongodb
    image: mongo:latest
    env_file:
      - .env
    networks:
      - internal
    ports:
      - ${MONGODB_PORT}:27017
    restart: always
    volumes:
      - mongodb-data:/data/db

networks:
  internal:
    
volumes:
  mongodb-data:
